### ISSUE TITLE
PIpe Error 

### ISSUE THREAD

**Issue by belhaji** [blmvxer/passgen#1]
hello i'm trying to pipe passgen result on aircrack but i got this error
python wordlists/passgen/passgen.py -l 13  | aircrack-ng capture.cap -w -

Traceback (most recent call last):
  File "wordlists/passgen/passgen.py", line 114, in <module>
    KeyGenerate()
  File "wordlists/passgen/passgen.py", line 16, in KeyGenerate
    print(result)
IOError: [Errno 32] Broken pipe

**Comment by blmvxer** [comment]
Run both with sudo or as su

**Comment by blmvxer** [comment]
If no other issues I'll close this issue.

Also for future reference the python version won't be updated in further, I implore you to try the julia version as it's faster and will be updated more often.
